name: pint-nix

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
    CARGO_NET_GIT_FETCH_WITH_CLI: 'true'

jobs:
  # Test access to essential-base and pint repos while they're private.
  repo-ssh-access:
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
              ${{ secrets.SSH_KEY_BASE }}
              ${{ secrets.SSH_KEY_PINT }}
      - name: Test essential-base access
        run: |
          git ls-remote ssh://git@github.com/essential-contributions/essential-base.git HEAD
      - name: Test pint access
        run: |
          git ls-remote ssh://git@github.com/essential-contributions/pint.git HEAD

  # Check the nix code is formatted.
  nix-fmt-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: DeterminateSystems/nix-installer-action@main
    - run: nix fmt -- --check ./

  # Check the default builds work on both macOS and Linux.
  nix-build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        command: [
            "build --print-build-logs --no-update-lock-file"
          ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
              ${{ secrets.SSH_KEY_BASE }}
              ${{ secrets.SSH_KEY_PINT }}
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix ${{ matrix.command }}
