name: pint-nix

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # Test access to upstream repos while they're private.
  repo-ssh-access:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - repo: essential-base
          - repo: pint
    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          # Note: SSH_KEY_PINT_NIX may not be necessary, but trying everything.
          ssh-private-key: |
              ${{ secrets.SSH_KEY_BASE }}
              ${{ secrets.SSH_KEY_PINT }}
              ${{ secrets.SSH_KEY_PINT_NIX }}
      - run: |
          git ls-remote ssh://git@github.com/essential-contributions/${{ matrix.repo }}.git HEAD

  # Check the nix code is formatted.
  nix-fmt-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: DeterminateSystems/nix-installer-action@v10
    - uses: DeterminateSystems/magic-nix-cache-action@v4
    - run: nix fmt -- --check ./

  # Check the default builds and dev envs work on both macOS and Linux.
  nix:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        command: [
            "build --print-build-logs --no-update-lock-file",
            "develop --print-build-logs --no-update-lock-file",
          ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
              ${{ secrets.SSH_KEY_BASE }}
              ${{ secrets.SSH_KEY_PINT }}
              ${{ secrets.SSH_KEY_PINT_NIX }}
      - uses: DeterminateSystems/nix-installer-action@v10
      - uses: DeterminateSystems/magic-nix-cache-action@v4
      - run: nix ${{ matrix.command }}
